<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ["code" => '7901', "name" => 'Afganistán', "iso_code" => 'AF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7902', "name" => 'Albania', "iso_code" => 'AL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7903', "name" => 'Alemania', "iso_code" => 'DE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7904', "name" => 'Andorra', "iso_code" => 'AD',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7905', "name" => 'Angola', "iso_code" => 'AO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7906', "name" => 'Anguila', "iso_code" => 'AI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7907', "name" => 'Antártida', "iso_code" => 'AQ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7908', "name" => 'Antigua y Barbuda', "iso_code" => 'AG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7909', "name" => 'Arabia Saudí', "iso_code" => 'SA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7910', "name" => 'Argelia', "iso_code" => 'DZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7911', "name" => 'Argentina', "iso_code" => 'AR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7912', "name" => 'Armenia', "iso_code" => 'AM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7913', "name" => 'Aruba', "iso_code" => 'AW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7914', "name" => 'Australia', "iso_code" => 'AU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7915', "name" => 'Austria', "iso_code" => 'AT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7916', "name" => 'Azerbaiyán', "iso_code" => 'AZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7917', "name" => 'Bahamas', "iso_code" => 'BS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7918', "name" => 'Bangladés', "iso_code" => 'BD',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7919', "name" => 'Barbados', "iso_code" => 'BB',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7920', "name" => 'Baréin', "iso_code" => 'BH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7921', "name" => 'Bélgica', "iso_code" => 'BE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7922', "name" => 'Belice', "iso_code" => 'BZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7923', "name" => 'Benín', "iso_code" => 'BJ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7924', "name" => 'Bermudas', "iso_code" => 'BM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7925', "name" => 'Bielorrusia', "iso_code" => 'BY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7926', "name" => 'Bolivia', "iso_code" => 'BO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7927', "name" => 'Bosnia y Herzegovina', "iso_code" => 'BA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7928', "name" => 'Botsuana', "iso_code" => 'BW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7929', "name" => 'Brasil', "iso_code" => 'BR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7930', "name" => 'Brunéi', "iso_code" => 'BN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7931', "name" => 'Bulgaria', "iso_code" => 'BG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7932', "name" => 'Burkina Faso', "iso_code" => 'BF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7933', "name" => 'Burundi', "iso_code" => 'BI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7934', "name" => 'Bután', "iso_code" => 'BT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7935', "name" => 'Cabo Verde', "iso_code" => 'CV',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7936', "name" => 'Camboya', "iso_code" => 'KH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7937', "name" => 'Camerún', "iso_code" => 'CM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7938', "name" => 'Canadá', "iso_code" => 'CA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7939', "name" => 'Caribe neerlandés', "iso_code" => 'BQ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7940', "name" => 'Catar', "iso_code" => 'QA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7941', "name" => 'Chad', "iso_code" => 'TD',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7942', "name" => 'Chequia', "iso_code" => 'CZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7943', "name" => 'Chile', "iso_code" => 'CL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7944', "name" => 'China', "iso_code" => 'CN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7945', "name" => 'Chipre', "iso_code" => 'CY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7946', "name" => 'Ciudad del Vaticano', "iso_code" => 'VA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7947', "name" => 'Colombia', "iso_code" => 'CO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7948', "name" => 'Comoras', "iso_code" => 'KM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7949', "name" => 'Congo', "iso_code" => 'CG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7950', "name" => 'Corea del Norte', "iso_code" => 'KP',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7951', "name" => 'Corea del Sur', "iso_code" => 'KR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7952', "name" => 'Costa Rica', "iso_code" => 'CR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7953', "name" => 'Côte d’Ivoire', "iso_code" => 'CI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7954', "name" => 'Croacia', "iso_code" => 'HR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7955', "name" => 'Cuba', "iso_code" => 'CU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7956', "name" => 'Curazao', "iso_code" => 'CW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7957', "name" => 'Dinamarca', "iso_code" => 'DK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7958', "name" => 'Dominica', "iso_code" => 'DM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7959', "name" => 'Ecuador', "iso_code" => 'EC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7960', "name" => 'Egipto', "iso_code" => 'EG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7961', "name" => 'El Salvador', "iso_code" => 'SV',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7962', "name" => 'Emiratos Árabes Unidos', "iso_code" => 'AE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7963', "name" => 'Eritrea', "iso_code" => 'ER',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7964', "name" => 'Eslovaquia', "iso_code" => 'SK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7965', "name" => 'Eslovenia', "iso_code" => 'SI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7966', "name" => 'España', "iso_code" => 'ES',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7967', "name" => 'Estados Unidos', "iso_code" => 'US',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7968', "name" => 'Estonia', "iso_code" => 'EE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7969', "name" => 'Esuatini', "iso_code" => 'SZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7970', "name" => 'Etiopía', "iso_code" => 'ET',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7971', "name" => 'Filipinas', "iso_code" => 'PH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7972', "name" => 'Finlandia', "iso_code" => 'FI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7973', "name" => 'Fiyi', "iso_code" => 'FJ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7974', "name" => 'Francia', "iso_code" => 'FR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7975', "name" => 'Gabón', "iso_code" => 'GA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7976', "name" => 'Gambia', "iso_code" => 'GM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7977', "name" => 'Georgia', "iso_code" => 'GE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7978', "name" => 'Ghana', "iso_code" => 'GH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7979', "name" => 'Gibraltar', "iso_code" => 'GI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7980', "name" => 'Granada', "iso_code" => 'GD',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7981', "name" => 'Grecia', "iso_code" => 'GR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7982', "name" => 'Groenlandia', "iso_code" => 'GL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7983', "name" => 'Guadalupe', "iso_code" => 'GP',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7984', "name" => 'Guam', "iso_code" => 'GU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7985', "name" => 'Guatemala', "iso_code" => 'GT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7986', "name" => 'Guayana Francesa', "iso_code" => 'GF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7987', "name" => 'Guernsey', "iso_code" => 'GG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7988', "name" => 'Guinea', "iso_code" => 'GN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7989', "name" => 'Guinea Ecuatorial', "iso_code" => 'GQ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7990', "name" => 'Guinea-Bisáu', "iso_code" => 'GW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7991', "name" => 'Guyana', "iso_code" => 'GY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7992', "name" => 'Haití', "iso_code" => 'HT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7993', "name" => 'Honduras', "iso_code" => 'HN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7994', "name" => 'Hungría', "iso_code" => 'HU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7995', "name" => 'India', "iso_code" => 'IN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7996', "name" => 'Indonesia', "iso_code" => 'ID',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7997', "name" => 'Irak', "iso_code" => 'IQ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7998', "name" => 'Irán', "iso_code" => 'IR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '7999', "name" => 'Irlanda', "iso_code" => 'IE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8000', "name" => 'Isla Bouvet', "iso_code" => 'BV',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8001', "name" => 'Isla de Man', "iso_code" => 'IM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8002', "name" => 'Isla de Navidad', "iso_code" => 'CX',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8003', "name" => 'Isla Norfolk', "iso_code" => 'NF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8004', "name" => 'Islandia', "iso_code" => 'IS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8005', "name" => 'Islas Åland', "iso_code" => 'AX',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8006', "name" => 'Islas Caimán', "iso_code" => 'KY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8007', "name" => 'Islas Cocos', "iso_code" => 'CC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8008', "name" => 'Islas Cook', "iso_code" => 'CK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8009', "name" => 'Islas Feroe', "iso_code" => 'FO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8010', "name" => 'Islas Georgia del Sur y Sandwich del Sur', "iso_code" => 'GS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8011', "name" => 'Islas Heard y McDonald', "iso_code" => 'HM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8012', "name" => 'Islas Malvinas', "iso_code" => 'FK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8013', "name" => 'Islas Marianas del Norte', "iso_code" => 'MP',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8014', "name" => 'Islas Marshall', "iso_code" => 'MH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8015', "name" => 'Islas menores alejadas de EE. UU.', "iso_code" => 'UM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8016', "name" => 'Islas Pitcairn', "iso_code" => 'PN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8017', "name" => 'Islas Salomón', "iso_code" => 'SB',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8018', "name" => 'Islas Turcas y Caicos', "iso_code" => 'TC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8019', "name" => 'Islas Vírgenes Británicas', "iso_code" => 'VG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8020', "name" => 'Islas Vírgenes de EE. UU.', "iso_code" => 'VI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8021', "name" => 'Israel', "iso_code" => 'IL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8022', "name" => 'Italia', "iso_code" => 'IT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8023', "name" => 'Jamaica', "iso_code" => 'JM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8024', "name" => 'Japón', "iso_code" => 'JP',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8025', "name" => 'Jersey', "iso_code" => 'JE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8026', "name" => 'Jordania', "iso_code" => 'JO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8027', "name" => 'Kazajistán', "iso_code" => 'KZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8028', "name" => 'Kenia', "iso_code" => 'KE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8029', "name" => 'Kirguistán', "iso_code" => 'KG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8030', "name" => 'Kiribati', "iso_code" => 'KI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8031', "name" => 'Kuwait', "iso_code" => 'KW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8032', "name" => 'Laos', "iso_code" => 'LA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8033', "name" => 'Lesoto', "iso_code" => 'LS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8034', "name" => 'Letonia', "iso_code" => 'LV',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8035', "name" => 'Líbano', "iso_code" => 'LB',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8036', "name" => 'Liberia', "iso_code" => 'LR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8037', "name" => 'Libia', "iso_code" => 'LY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8038', "name" => 'Liechtenstein', "iso_code" => 'LI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8039', "name" => 'Lituania', "iso_code" => 'LT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8040', "name" => 'Luxemburgo', "iso_code" => 'LU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8041', "name" => 'Macedonia del Norte', "iso_code" => 'MK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8042', "name" => 'Madagascar', "iso_code" => 'MG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8043', "name" => 'Malasia', "iso_code" => 'MY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8044', "name" => 'Malaui', "iso_code" => 'MW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8045', "name" => 'Maldivas', "iso_code" => 'MV',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8046', "name" => 'Mali', "iso_code" => 'ML',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8047', "name" => 'Malta', "iso_code" => 'MT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8048', "name" => 'Marruecos', "iso_code" => 'MA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8049', "name" => 'Martinica', "iso_code" => 'MQ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8050', "name" => 'Mauricio', "iso_code" => 'MU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8051', "name" => 'Mauritania', "iso_code" => 'MR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8052', "name" => 'Mayotte', "iso_code" => 'YT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8053', "name" => 'México', "iso_code" => 'MX',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8054', "name" => 'Micronesia', "iso_code" => 'FM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8055', "name" => 'Moldavia', "iso_code" => 'MD',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8056', "name" => 'Mónaco', "iso_code" => 'MC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8057', "name" => 'Mongolia', "iso_code" => 'MN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8058', "name" => 'Montenegro', "iso_code" => 'ME',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8059', "name" => 'Montserrat', "iso_code" => 'MS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8060', "name" => 'Mozambique', "iso_code" => 'MZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8061', "name" => 'Myanmar (Birmania)', "iso_code" => 'MM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8062', "name" => 'Namibia', "iso_code" => 'NA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8063', "name" => 'Nauru', "iso_code" => 'NR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8064', "name" => 'Nepal', "iso_code" => 'NP',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8065', "name" => 'Nicaragua', "iso_code" => 'NI',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8066', "name" => 'Níger', "iso_code" => 'NE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8067', "name" => 'Nigeria', "iso_code" => 'NG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8068', "name" => 'Niue', "iso_code" => 'NU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8069', "name" => 'Noruega', "iso_code" => 'NO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8070', "name" => 'Nueva Caledonia', "iso_code" => 'NC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8071', "name" => 'Nueva Zelanda', "iso_code" => 'NZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8072', "name" => 'Omán', "iso_code" => 'OM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8073', "name" => 'Países Bajos', "iso_code" => 'NL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8074', "name" => 'Pakistán', "iso_code" => 'PK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8075', "name" => 'Palaos', "iso_code" => 'PW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8076', "name" => 'Panamá', "iso_code" => 'PA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8077', "name" => 'Papúa Nueva Guinea', "iso_code" => 'PG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8078', "name" => 'Paraguay', "iso_code" => 'PY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8079', "name" => 'Perú', "iso_code" => 'PE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8080', "name" => 'Polinesia Francesa', "iso_code" => 'PF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8081', "name" => 'Polonia', "iso_code" => 'PL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8082', "name" => 'Portugal', "iso_code" => 'PT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8083', "name" => 'Puerto Rico', "iso_code" => 'PR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8084', "name" => 'RAE de Hong Kong (China)', "iso_code" => 'HK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8085', "name" => 'RAE de Macao (China)', "iso_code" => 'MO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8086', "name" => 'Reino Unido', "iso_code" => 'GB',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8087', "name" => 'República Centroafricana', "iso_code" => 'CF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8088', "name" => 'República Democrática del Congo', "iso_code" => 'CD',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8089', "name" => 'República Dominicana', "iso_code" => 'DO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8090', "name" => 'Reunión', "iso_code" => 'RE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8091', "name" => 'Ruanda', "iso_code" => 'RW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8092', "name" => 'Rumanía', "iso_code" => 'RO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8093', "name" => 'Rusia', "iso_code" => 'RU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8094', "name" => 'Sáhara Occidental', "iso_code" => 'EH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8095', "name" => 'Samoa', "iso_code" => 'WS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8096', "name" => 'Samoa Americana', "iso_code" => 'AS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8097', "name" => 'San Bartolomé', "iso_code" => 'BL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8098', "name" => 'San Cristóbal y Nieves', "iso_code" => 'KN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8099', "name" => 'San Marino', "iso_code" => 'SM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8100', "name" => 'San Martín', "iso_code" => 'MF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8101', "name" => 'San Pedro y Miquelón', "iso_code" => 'PM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8102', "name" => 'San Vicente y las Granadinas', "iso_code" => 'VC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8103', "name" => 'Santa Elena', "iso_code" => 'SH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8104', "name" => 'Santa Lucía', "iso_code" => 'LC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8105', "name" => 'Santo Tomé y Príncipe', "iso_code" => 'ST',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8106', "name" => 'Senegal', "iso_code" => 'SN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8107', "name" => 'Serbia', "iso_code" => 'RS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8108', "name" => 'Seychelles', "iso_code" => 'SC',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8109', "name" => 'Sierra Leona', "iso_code" => 'SL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8110', "name" => 'Singapur', "iso_code" => 'SG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8111', "name" => 'Sint Maarten', "iso_code" => 'SX',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8112', "name" => 'Siria', "iso_code" => 'SY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8113', "name" => 'Somalia', "iso_code" => 'SO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8114', "name" => 'Sri Lanka', "iso_code" => 'LK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8115', "name" => 'Sudáfrica', "iso_code" => 'ZA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8116', "name" => 'Sudán', "iso_code" => 'SD',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8117', "name" => 'Sudán del Sur', "iso_code" => 'SS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8118', "name" => 'Suecia', "iso_code" => 'SE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8119', "name" => 'Suiza', "iso_code" => 'CH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8120', "name" => 'Surinam', "iso_code" => 'SR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8121', "name" => 'Svalbard y Jan Mayen', "iso_code" => 'SJ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8122', "name" => 'Tailandia', "iso_code" => 'TH',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8123', "name" => 'Taiwán', "iso_code" => 'TW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8124', "name" => 'Tanzania', "iso_code" => 'TZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8125', "name" => 'Tayikistán', "iso_code" => 'TJ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8126', "name" => 'Territorio Británico del Océano Índico', "iso_code" => 'IO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8127', "name" => 'Territorios Australes Franceses', "iso_code" => 'TF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8128', "name" => 'Territorios Palestinos', "iso_code" => 'PS',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8129', "name" => 'Timor-Leste', "iso_code" => 'TL',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8130', "name" => 'Togo', "iso_code" => 'TG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8131', "name" => 'Tokelau', "iso_code" => 'TK',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8132', "name" => 'Tonga', "iso_code" => 'TO',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8133', "name" => 'Trinidad y Tobago', "iso_code" => 'TT',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8134', "name" => 'Túnez', "iso_code" => 'TN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8135', "name" => 'Turkmenistán', "iso_code" => 'TM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8136', "name" => 'Turquía', "iso_code" => 'TR',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8137', "name" => 'Tuvalu', "iso_code" => 'TV',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8138', "name" => 'Ucrania', "iso_code" => 'UA',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8139', "name" => 'Uganda', "iso_code" => 'UG',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8140', "name" => 'Uruguay', "iso_code" => 'UY',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8141', "name" => 'Uzbekistán', "iso_code" => 'UZ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8142', "name" => 'Vanuatu', "iso_code" => 'VU',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8143', "name" => 'Venezuela', "iso_code" => 'VE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8144', "name" => 'Vietnam', "iso_code" => 'VN',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8145', "name" => 'Wallis y Futuna', "iso_code" => 'WF',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8146', "name" => 'Yemen', "iso_code" => 'YE',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8147', "name" => 'Yibuti', "iso_code" => 'DJ',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8148', "name" => 'Zambia', "iso_code" => 'ZM',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            ["code" => '8149', "name" => 'Zimbabue', "iso_code" => 'ZW',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
        ]);
    }
}