<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class DistritosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('distritos')->insert([
            [ "name" =>' Santo Domingo de Guzman', "code" =>'151501', "province_code" =>' 6801', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Azua', "code" =>'151502', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Barro Arriba (DM)', "code" =>'151503', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Barias-La Estancia (DM)', "code" =>'151504', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Jovillos  (DM)', "code" =>'151505', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Puerto Viejo (DM)', "code" =>'151506', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Barreras  (DM)', "code" =>'151507', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Dona Emma Balaguer Viuda Vallejo (DM)', "code" =>'151508', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Clavellina (DM)', "code" =>'151509', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Lomas (DM)', "code" =>'151510', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Charcas', "code" =>'151511', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Palmar de Ocoa (DM)', "code" =>'151512', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Yayas de Viajama', "code" =>'151513', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villarpando (DM)', "code" =>'151514', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hato Nuevo Cortes (DM)', "code" =>'151515', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Padre Las Casas', "code" =>'151516', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Lagunas (DM)', "code" =>'151517', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Siembra (DM)', "code" =>'151518', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Monte Bonito (DM)', "code" =>'151519', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Frios (DM)', "code" =>'151520', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Peralta', "code" =>'151521', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Yegua', "code" =>'151522', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Proyecto 4 (DM)', "code" =>'151523', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Ganadero (DM)', "code" =>'151524', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Proyecto 2-C (DM)', "code" =>'151525', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pueblo Viejo', "code" =>'151526', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Rosario (DM)', "code" =>'151527', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Tabara Arriba', "code" =>'151528', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Tabara Abajo (DM)', "code" =>'151529', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Amiama Gomez (DM)', "code" =>'151530', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Toros (DM)', "code" =>'151531', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guayabal', "code" =>'151532', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Estebania', "code" =>'151533', "province_code" =>' 6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Neiba', "code" =>'151534', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Palmar  (DM)', "code" =>'151535', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Galvan', "code" =>'151536', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Salado (DM)', "code" =>'151537', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Tamayo', "code" =>'151538', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Uvilla (DM)', "code" =>'151539', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santana (DM)', "code" =>'151540', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Monserrate o Montserrat (DM)', "code" =>'151541', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cabeza de Toro (DM)', "code" =>'151542', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Mena (DM)', "code" =>'151543', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santa Barbara El 6 (DM)', "code" =>'151544', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Jaragua', "code" =>'151545', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Rios', "code" =>'151546', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Clavellinas (DM)', "code" =>'151547', "province_code" =>' 6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Barahona', "code" =>'151548', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Cachon (DM)', "code" =>'151549', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Guazara (DM)', "code" =>'151550', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Central (DM)', "code" =>'151551', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cabral', "code" =>'151552', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Enriquillo', "code" =>'151553', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Arroyo Dulce (DM)', "code" =>'151554', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Paraiso', "code" =>'151555', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Patos (DM)', "code" =>'151556', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Vicente Noble', "code" =>'151557', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Canoa (DM)', "code" =>'151558', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Quita Coraza (DM)', "code" =>'151559', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Fondo Negro (DM)', "code" =>'151560', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Penon', "code" =>'151561', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Cienaga', "code" =>'151562', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Baoruco (DM)', "code" =>'151563', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Fundacion', "code" =>'151564', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pescaderia (DM)', "code" =>'151565', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Salinas', "code" =>'151566', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Polo', "code" =>'151567', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jaquimeyes', "code" =>'151568', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Palo Alto (DM)', "code" =>'151569', "province_code" =>' 6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Dajabon', "code" =>'151570', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cañongo (DM)', "code" =>'151571', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Loma de Cabrera', "code" =>'151572', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Capotillo (DM)', "code" =>'151573', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santiago de La Cruz (DM)', "code" =>'151574', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Partido', "code" =>'151575', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Restauracion', "code" =>'151576', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Pino', "code" =>'151577', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Manuel Bueno (DM)', "code" =>'151578', "province_code" =>' 6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Francisco de Macoris', "code" =>'151579', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Peña (DM)', "code" =>'151580', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cenovi (DM)', "code" =>'151581', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jaya (DM)', "code" =>'151582', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Presidente Don Antonio Guzman Fernandez (DM)', "code" =>'151583', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Arenoso', "code" =>'151584', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Coles (DM)', "code" =>'151585', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Aguacate (DM)', "code" =>'151586', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Castillo', "code" =>'151587', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pimentel', "code" =>'151588', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Riva', "code" =>'151589', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Agua Santa del Yuna  (DM)', "code" =>'151590', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cristo Rey de Guaraguao (DM)', "code" =>'151591', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Taranas (DM)', "code" =>'151592', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Barraquito (DM)', "code" =>'151593', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Guaranas', "code" =>'151594', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Eugenio Maria de Hostos', "code" =>'151595', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Grande (DM)', "code" =>'151596', "province_code" =>' 6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Comendador', "code" =>'151597', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Larga (DM)', "code" =>'151598', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guayabo (DM)', "code" =>'151599', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Banica', "code" =>'151600', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Cruz (DM)', "code" =>'151601', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Higuero (DM)', "code" =>'151602', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Llano', "code" =>'151603', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guanito (DM)', "code" =>'151604', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hondo Valle', "code" =>'151605', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Rancho de La Guardia (DM)', "code" =>'151606', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pedro Santana', "code" =>'151607', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Rio Limpio (DM)', "code" =>'151608', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Juan Santiago', "code" =>'151609', "province_code" =>' 6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Seibo', "code" =>'151610', "province_code" =>' 6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pedro Sanchez (DM)', "code" =>'151611', "province_code" =>' 6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Francisco-Vicentillo (DM)', "code" =>'151612', "province_code" =>' 6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santa Lucia (DM)', "code" =>'151613', "province_code" =>' 6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Lagunas (DM)', "code" =>'151614', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Duverge', "code" =>'151615', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Miches', "code" =>'151616', "province_code" =>' 6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cristobal', "code" =>'151617', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Cedro (DM)', "code" =>'151618', "province_code" =>' 6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Canca la Reyna (DM)', "code" =>'151619', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Ortega (DM)', "code" =>'151620', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jimani', "code" =>'151621', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Limon (DM)', "code" =>'151622', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Postrer Rio', "code" =>'151623', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Boca de Yuma (DM)', "code" =>'151624', "province_code" =>' 6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Gina (DM)', "code" =>'151625', "province_code" =>' 6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Gaspar Hernandez', "code" =>'151626', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Boca de Cachon (DM)', "code" =>'151627', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Higuey', "code" =>'151628', "province_code" =>' 6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Hermosa', "code" =>'151629', "province_code" =>' 6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cumayasa (DM)', "code" =>'151630', "province_code" =>' 6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Moca', "code" =>'151631', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Victor', "code" =>'151632', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Vengan a Ver (DM)', "code" =>'151633', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Mella', "code" =>'151634', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Rafael del Yuma', "code" =>'151635', "province_code" =>' 6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jose Contreras (DM)', "code" =>'151636', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Juan Lopez (DM)', "code" =>'151637', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Descubierta', "code" =>'151638', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Batey 8 (DM)', "code" =>'151639', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Higuerito (DM)', "code" =>'151640', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Monte de la Jagua (DM)', "code" =>'151641', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guayabal (DM)', "code" =>'151642', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Otra Banda (DM)', "code" =>'151643', "province_code" =>' 6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Romana', "code" =>'151644', "province_code" =>' 6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cayetano Germosen', "code" =>'151645', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jamao Al Norte', "code" =>'151646', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Colonia (DM)', "code" =>'151647', "province_code" =>' 6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Lagunas de Nisibon (DM)', "code" =>'151648', "province_code" =>' 6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Vega', "code" =>'151649', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Joba Arriba (DM)', "code" =>'151650', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Veragua (DM)', "code" =>'151651', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Magante (DM)', "code" =>'151652', "province_code" =>' 6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Veron Punta Cana (DM)', "code" =>'151653', "province_code" =>' 6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Bayahibe (DM)', "code" =>'151654', "province_code" =>' 6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Caleta (DM)', "code" =>'151655', "province_code" =>' 6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guaymate', "code" =>'151656', "province_code" =>' 6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Rio Verde Arriba (DM)', "code" =>'151657', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Ranchito (DM)', "code" =>'151658', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Tavera (DM)', "code" =>'151659', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Don Juan Rodriguez (DM)', "code" =>'151660', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Constanza', "code" =>'151661', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Tireo (DM)', "code" =>'151662', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Sabina (DM)', "code" =>'151663', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jarabacoa', "code" =>'151664', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Buena Vista (DM)', "code" =>'151665', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Manabao (DM)', "code" =>'151666', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jima Abajo', "code" =>'151667', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Rincon (DM)', "code" =>'151668', "province_code" =>' 6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Nagua', "code" =>'151669', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Jose de Matanzas (DM)', "code" =>'151670', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Gordas (DM)', "code" =>'151671', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Arroyo al Medio (DM)', "code" =>'151672', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cabrera', "code" =>'151673', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Arroyo Salado (DM)', "code" =>'151674', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Entrada (DM)', "code" =>'151675', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Factor', "code" =>'151676', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Pozo (DM)', "code" =>'151677', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Rio San Juan', "code" =>'151678', "province_code" =>' 6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Monte Cristi', "code" =>'151679', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Castañuelas', "code" =>'151680', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Palo Verde (DM)', "code" =>'151681', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guayubin', "code" =>'151682', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Elisa (DM)', "code" =>'151683', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hatillo Palma (DM)', "code" =>'151684', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cana Chapeton (DM)', "code" =>'151685', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Matas de Santa Cruz', "code" =>'151686', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pepillo Salcedo o Manzanillo', "code" =>'151687', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santa Maria (DM)', "code" =>'151688', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Vasquez', "code" =>'151689', "province_code" =>' 6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pedernales', "code" =>'151690', "province_code" =>' 6816', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jose Francisco Peña Gomez (DM)', "code" =>'151691', "province_code" =>' 6816', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Oviedo', "code" =>'151692', "province_code" =>' 6816', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Juancho (DM)', "code" =>'151693', "province_code" =>' 6816', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Bani', "code" =>'151694', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Fundacion (DM)', "code" =>'151695', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Buey (DM)', "code" =>'151696', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Paya (DM)', "code" =>'151697', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Sombrero (DM)', "code" =>'151698', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Carreton (DM)', "code" =>'151699', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Catalina (DM)', "code" =>'151700', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Limonal (DM)', "code" =>'151701', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Barias (DM)', "code" =>'151702', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Nizao', "code" =>'151703', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pizarrete (DM)', "code" =>'151704', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santana (DM)', "code" =>'151705', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Matanzas', "code" =>'151706', "province_code" =>' 6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Puerto Plata', "code" =>'151707', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Yasica Arriba (DM)', "code" =>'151708', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Maimon (DM)', "code" =>'151709', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Altamira', "code" =>'151710', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Rio Grande (DM)', "code" =>'151711', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guananico', "code" =>'151712', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Imbert', "code" =>'151713', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Hidalgos', "code" =>'151714', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Navas (DM)', "code" =>'151715', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Luperon', "code" =>'151716', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Isabela (DM)', "code" =>'151717', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Belloso (DM)', "code" =>'151718', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Estrecho de Luperon Omar Bross (DM)', "code" =>'151719', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sosua', "code" =>'151720', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cabarete (DM)', "code" =>'151721', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabaneta de Yasica (DM)', "code" =>'151722', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Isabela', "code" =>'151723', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Estero Hondo (DM)', "code" =>'151724', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Jaiba (DM)', "code" =>'151725', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Gualete (DM)', "code" =>'151726', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Montellano', "code" =>'151727', "province_code" =>' 6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Salcedo', "code" =>'151728', "province_code" =>' 6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jamao Afuera (DM)', "code" =>'151729', "province_code" =>' 6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Tenares', "code" =>'151730', "province_code" =>' 6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Blanco (DM)', "code" =>'151731', "province_code" =>' 6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Tapia', "code" =>'151732', "province_code" =>' 6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Samana', "code" =>'151733', "province_code" =>' 6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Limon (DM)', "code" =>'151734', "province_code" =>' 6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Arroyo Barril (DM)', "code" =>'151735', "province_code" =>' 6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Galeras (DM)', "code" =>'151736', "province_code" =>' 6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sanchez', "code" =>'151737', "province_code" =>' 6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Terrenas', "code" =>'151738', "province_code" =>' 6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Cristobal', "code" =>'151739', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hato Damas (DM)', "code" =>'151740', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hatillo (DM)', "code" =>'151741', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Grande de Palenque', "code" =>'151742', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Bajos de Haina', "code" =>'151743', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Carril (DM)', "code" =>'151744', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Quita Sueño (DM)', "code" =>'151745', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cambita Garabitos', "code" =>'151746', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cambita El Pueblecito (DM)', "code" =>'151747', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Altagracia', "code" =>'151748', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Jose del Puerto (DM)', "code" =>'151749', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Medina (DM)', "code" =>'151750', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Cuchilla (DM)', "code" =>'151751', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Yaguate', "code" =>'151752', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Doña Ana (DM)', "code" =>'151753', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Gregorio de Nigua', "code" =>'151754', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Cacaos', "code" =>'151755', "province_code" =>' 6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Juan', "code" =>'151756', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pedro Corto (DM)', "code" =>'151757', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabaneta (DM)', "code" =>'151758', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Alta (DM)', "code" =>'151759', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Rosario (DM)', "code" =>'151760', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hato del Padre (DM)', "code" =>'151761', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guanito (DM)', "code" =>'151762', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Jagua (DM)', "code" =>'151763', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Arroyo Cano (DM)', "code" =>'151764', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Pedro de Macoris', "code" =>'151765', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Maguanas-Hato Nuevo (DM)', "code" =>'151766', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Llanos', "code" =>'151767', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Consuelo', "code" =>'151768', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cotui', "code" =>'151769', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Charcas de Maria Nova (DM)', "code" =>'151770', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Quisqueya', "code" =>'151771', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guayacanes', "code" =>'151772', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Zanjas (DM)', "code" =>'151773', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Derrumbadero (DM)', "code" =>'151774', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Comedero Arriba (DM)', "code" =>'151775', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Bija (DM)', "code" =>'151776', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hernando Alonzo (DM)', "code" =>'151777', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Bohechio', "code" =>'151778', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Angelina (DM)', "code" =>'151779', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Yaque (DM)', "code" =>'151780', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Matayaya (DM)', "code" =>'151781', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Ramon Santana', "code" =>'151782', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Quita Sueño (DM)', "code" =>'151783', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Zambrana Abajo (DM)', "code" =>'151784', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pedro Garcia (DM)', "code" =>'151785', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hato del Yaque (DM)', "code" =>'151786', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santiago Oeste (DM)', "code" =>'151787', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Bisono', "code" =>'151788', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Cercado', "code" =>'151789', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Matas de Farfan', "code" =>'151790', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jorjillo (DM)', "code" =>'151791', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Puerto (DM)', "code" =>'151792', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Gautier (DM)', "code" =>'151793', "province_code" =>' 6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Platanal  (DM)', "code" =>'151794', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Cueva (DM)', "code" =>'151795', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Batista (DM)', "code" =>'151796', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jinova (DM)', "code" =>'151797', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Vallejuelo', "code" =>'151798', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cevicos', "code" =>'151799', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Francisco de Jacagua (DM)', "code" =>'151800', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Juan de Herrera', "code" =>'151801', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa La Mata', "code" =>'151802', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santiago', "code" =>'151803', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Canela (DM)', "code" =>'151804', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Carrera de Yeguas (DM)', "code" =>'151805', "province_code" =>' 6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Caballero (DM)', "code" =>'151806', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Fantino', "code" =>'151807', "province_code" =>' 6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Janico', "code" =>'151808', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Juncalito (DM)', "code" =>'151809', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Caimito (DM)', "code" =>'151810', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Licey al Medio', "code" =>'151811', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Palomas (DM)', "code" =>'151812', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Jose de Las Matas', "code" =>'151813', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Rubio (DM)', "code" =>'151814', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Cuesta (DM)', "code" =>'151815', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Las Placetas (DM)', "code" =>'151816', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Tamboril', "code" =>'151817', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Canca La Piedra (DM)', "code" =>'151818', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Gonzalez', "code" =>'151819', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Palmar Arriba (DM)', "code" =>'151820', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Limon (DM)', "code" =>'151821', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Puñal', "code" =>'151822', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guayabal (DM)', "code" =>'151823', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Canabacoa (DM)', "code" =>'151824', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Iglesia', "code" =>'151825', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Baitoa', "code" =>'151826', "province_code" =>' 6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Ignacio de Sabaneta', "code" =>'151827', "province_code" =>' 6826', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa Los Almacigos', "code" =>'151828', "province_code" =>' 6826', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Moncion', "code" =>'151829', "province_code" =>' 6826', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Mao', "code" =>'151830', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Amina (DM)', "code" =>'151831', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jaibon o Pueblo Nuevo (DM)', "code" =>'151832', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guatapanal (DM)', "code" =>'151833', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Esperanza', "code" =>'151834', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Maizal (DM)', "code" =>'151835', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jicome (DM)', "code" =>'151836', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Boca de Mao (DM)', "code" =>'151837', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Paradero (DM)', "code" =>'151838', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Laguna Salada', "code" =>'151839', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jaibon (DM)', "code" =>'151840', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Caya (DM)', "code" =>'151841', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Cruce de Guayacanes (DM)', "code" =>'151842', "province_code" =>' 6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Bonao', "code" =>'151843', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana del Puerto (DM)', "code" =>'151844', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Juma Bejucal (DM)', "code" =>'151845', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Arroyo  Toro - Masipedro (DM)', "code" =>'151846', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Jayaco (DM)', "code" =>'151847', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Salvia - Los Quemados (DM)', "code" =>'151848', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Maimon', "code" =>'151849', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Piedra Blanca', "code" =>'151850', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Villa de Sonador (DM)', "code" =>'151851', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Juan Adrian (DM)', "code" =>'151852', "province_code" =>' 6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Monte Plata', "code" =>'151853', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Don Juan (DM)', "code" =>'151854', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Chirino (DM)', "code" =>'151855', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Boya (DM)', "code" =>'151856', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Bayaguana', "code" =>'151857', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Grande de Boya', "code" =>'151858', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Gonzalo (DM)', "code" =>'151859', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Majagual (DM)', "code" =>'151860', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Yamasa', "code" =>'151861', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Botados (DM)', "code" =>'151862', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Mama Tingo (DM)', "code" =>'151863', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Peralvillo', "code" =>'151864', "province_code" =>' 6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hato Mayor', "code" =>'151865', "province_code" =>' 6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Yerba Buena (DM)', "code" =>'151866', "province_code" =>' 6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Mata Palacio (DM)', "code" =>'151867', "province_code" =>' 6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Guayabo Dulce (DM)', "code" =>'151868', "province_code" =>' 6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana de La Mar', "code" =>'151869', "province_code" =>' 6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Elupina Cordero de Las Cañitas (DM)', "code" =>'151870', "province_code" =>' 6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Valle', "code" =>'151871', "province_code" =>' 6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Jose de Ocoa', "code" =>'151872', "province_code" =>' 6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Cienaga (DM)', "code" =>'151873', "province_code" =>' 6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Nizao - Las Auyamas (DM)', "code" =>'151874', "province_code" =>' 6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Pinar (DM)', "code" =>'151875', "province_code" =>' 6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' El Naranjal (DM)', "code" =>'151876', "province_code" =>' 6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Sabana Larga', "code" =>'151877', "province_code" =>' 6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Rancho Arriba', "code" =>'151878', "province_code" =>' 6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santo Domingo Este', "code" =>'151879', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Luis (DM)', "code" =>'151880', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santo Domingo Oeste', "code" =>'151881', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Santo Domingo Norte', "code" =>'151882', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Victoria (DM)', "code" =>'151883', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Boca Chica', "code" =>'151884', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Caleta (DM)', "code" =>'151885', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' San Antonio de Guerra', "code" =>'151886', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Hato Viejo (DM)', "code" =>'151887', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Los Alcarrizos', "code" =>'151888', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Palmarejo-Villa Linda (DM)', "code" =>'151889', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pantoja (DM)', "code" =>'151890', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' Pedro Brand', "code" =>'151891', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Guayiga (DM)', "code" =>'151892', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' La Cuaba (DM)', "code" =>'151893', "province_code" =>' 6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151894', "province_code" =>' 6833', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151895', "province_code" =>' 6834', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151896', "province_code" =>' 6835', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151897', "province_code" =>' 6836', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151898', "province_code" =>' 6837', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151899', "province_code" =>' 6838', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151900', "province_code" =>' 6839', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151901', "province_code" =>' 6840', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151902', "province_code" =>' 6841', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151903', "province_code" =>' 6842', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151904', "province_code" =>' 6843', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151905', "province_code" =>' 6844', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151906', "province_code" =>' 6845', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151907', "province_code" =>' 6846', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151908', "province_code" =>' 6847', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151909', "province_code" =>' 6848', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151910', "province_code" =>' 6849', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151911', "province_code" =>' 6850', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151912', "province_code" =>' 6851', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151913', "province_code" =>' 6852', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151914', "province_code" =>' 6853', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151915', "province_code" =>' 6854', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151916', "province_code" =>' 6855', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151917', "province_code" =>' 6856', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151918', "province_code" =>' 6857', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151919', "province_code" =>' 6858', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151920', "province_code" =>' 6859', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151921', "province_code" =>' 6860', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151922', "province_code" =>' 6861', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151923', "province_code" =>' 6862', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151924', "province_code" =>' 6863', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151925', "province_code" =>' 6864', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151926', "province_code" =>' 6865', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151927', "province_code" =>' 6866', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151928', "province_code" =>' 6867', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151929', "province_code" =>' 6868', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151930', "province_code" =>' 6869', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151931', "province_code" =>' 6870', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151932', "province_code" =>' 6871', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151933', "province_code" =>' 6872', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151934', "province_code" =>' 6873', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151935', "province_code" =>' 6874', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151936', "province_code" =>' 6875', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151937', "province_code" =>' 6876', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151938', "province_code" =>' 6877', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151939', "province_code" =>' 6878', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151940', "province_code" =>' 6879', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151941', "province_code" =>' 6880', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151942', "province_code" =>' 6881', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151943', "province_code" =>' 6882', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151944', "province_code" =>' 6883', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151945', "province_code" =>' 6884', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151946', "province_code" =>' 6885', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151947', "province_code" =>' 6886', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151948', "province_code" =>' 6887', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151949', "province_code" =>' 6888', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151950', "province_code" =>' 6889', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151951', "province_code" =>' 6890', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151952', "province_code" =>' 6891', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151953', "province_code" =>' 6892', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151954', "province_code" =>' 6893', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151955', "province_code" =>' 6894', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151956', "province_code" =>' 6895', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151957', "province_code" =>' 6896', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151958', "province_code" =>' 6897', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151959', "province_code" =>' 6898', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151960', "province_code" =>' 6899', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151961', "province_code" =>' 6900', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151962', "province_code" =>' 6901', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151963', "province_code" =>' 6902', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151964', "province_code" =>' 6903', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151965', "province_code" =>' 6904', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151966', "province_code" =>' 6905', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151967', "province_code" =>' 6906', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151968', "province_code" =>' 6907', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151969', "province_code" =>' 6908', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151970', "province_code" =>' 6909', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151971', "province_code" =>' 6910', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151972', "province_code" =>' 6911', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151973', "province_code" =>' 6912', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151974', "province_code" =>' 6913', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151975', "province_code" =>' 6914', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151976', "province_code" =>' 6915', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151977', "province_code" =>' 6916', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151978', "province_code" =>' 6917', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151979', "province_code" =>' 6918', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151980', "province_code" =>' 6919', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151981', "province_code" =>' 6920', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151982', "province_code" =>' 6921', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151983', "province_code" =>' 6922', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151984', "province_code" =>' 6923', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151985', "province_code" =>' 6924', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151986', "province_code" =>' 6925', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151987', "province_code" =>' 6926', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151988', "province_code" =>' 6927', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151989', "province_code" =>' 6928', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151990', "province_code" =>' 6929', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151991', "province_code" =>' 6930', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151992', "province_code" =>' 6931', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151993', "province_code" =>' 6932', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151994', "province_code" =>' 6933', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151995', "province_code" =>' 6934', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151996', "province_code" =>' 6935', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151997', "province_code" =>' 6936', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151998', "province_code" =>' 6937', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'151999', "province_code" =>' 6938', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152000', "province_code" =>' 6939', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152001', "province_code" =>' 6940', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152002', "province_code" =>' 6941', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152003', "province_code" =>' 6942', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152004', "province_code" =>' 6943', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152005', "province_code" =>' 6944', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152006', "province_code" =>' 6945', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152007', "province_code" =>' 6946', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152008', "province_code" =>' 6947', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152009', "province_code" =>' 6948', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152010', "province_code" =>' 6949', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152011', "province_code" =>' 6950', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152012', "province_code" =>' 6951', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152013', "province_code" =>' 6952', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152014', "province_code" =>' 6953', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152015', "province_code" =>' 6954', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152016', "province_code" =>' 6955', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152017', "province_code" =>' 6956', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152018', "province_code" =>' 6957', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152019', "province_code" =>' 6958', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152020', "province_code" =>' 6959', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152021', "province_code" =>' 6960', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152022', "province_code" =>' 6961', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152023', "province_code" =>' 6962', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152024', "province_code" =>' 6963', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152025', "province_code" =>' 6964', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152026', "province_code" =>' 6965', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152027', "province_code" =>' 6966', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152028', "province_code" =>' 6967', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152029', "province_code" =>' 6968', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152030', "province_code" =>' 6969', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152031', "province_code" =>' 6970', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152032', "province_code" =>' 6971', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152033', "province_code" =>' 6972', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152034', "province_code" =>' 6973', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152035', "province_code" =>' 6974', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152036', "province_code" =>' 6975', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152037', "province_code" =>' 6976', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152038', "province_code" =>' 6977', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152039', "province_code" =>' 6978', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152040', "province_code" =>' 6979', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152041', "province_code" =>' 6980', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152042', "province_code" =>' 6981', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152043', "province_code" =>' 6982', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152044', "province_code" =>' 6983', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152045', "province_code" =>' 6984', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152046', "province_code" =>' 6985', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152047', "province_code" =>' 6986', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152048', "province_code" =>' 6987', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152049', "province_code" =>' 6988', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152050', "province_code" =>' 6989', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152051', "province_code" =>' 6990', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152052', "province_code" =>' 6991', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152053', "province_code" =>' 6992', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152054', "province_code" =>' 6993', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152055', "province_code" =>' 6994', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152056', "province_code" =>' 6995', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152057', "province_code" =>' 6996', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152058', "province_code" =>' 6997', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152059', "province_code" =>' 6998', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152060', "province_code" =>' 6999', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152061', "province_code" =>' 7000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152062', "province_code" =>' 7001', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152063', "province_code" =>' 7002', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152064', "province_code" =>' 7003', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152065', "province_code" =>' 7004', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152066', "province_code" =>' 7005', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152067', "province_code" =>' 7006', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152068', "province_code" =>' 7007', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152069', "province_code" =>' 7008', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152070', "province_code" =>' 7009', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152071', "province_code" =>' 7010', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152072', "province_code" =>' 7011', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152073', "province_code" =>' 7012', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152074', "province_code" =>' 7013', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152075', "province_code" =>' 7014', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152076', "province_code" =>' 7015', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152077', "province_code" =>' 7016', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152078', "province_code" =>' 7017', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152079', "province_code" =>' 7018', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152080', "province_code" =>' 7019', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152081', "province_code" =>' 7020', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152083', "province_code" =>' 7021', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152084', "province_code" =>' 7022', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152085', "province_code" =>' 7023', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152086', "province_code" =>' 7024', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152087', "province_code" =>' 7025', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152088', "province_code" =>' 7026', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152089', "province_code" =>' 7027', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152090', "province_code" =>' 7028', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152091', "province_code" =>' 7029', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152092', "province_code" =>' 7030', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152093', "province_code" =>' 7031', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152094', "province_code" =>' 7032', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152095', "province_code" =>' 7033', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152096', "province_code" =>' 7034', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152097', "province_code" =>' 7035', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152098', "province_code" =>' 7036', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152099', "province_code" =>' 7037', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152100', "province_code" =>' 7038', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152101', "province_code" =>' 7039', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152102', "province_code" =>' 7040', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152103', "province_code" =>' 7041', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152104', "province_code" =>' 7042', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152105', "province_code" =>' 7043', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152106', "province_code" =>' 7044', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152107', "province_code" =>' 7045', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152108', "province_code" =>' 7046', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152109', "province_code" =>' 7047', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152110', "province_code" =>' 7048', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152111', "province_code" =>' 7049', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152112', "province_code" =>' 7050', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152113', "province_code" =>' 7051', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152114', "province_code" =>' 7052', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152115', "province_code" =>' 7053', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152116', "province_code" =>' 7054', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152117', "province_code" =>' 7055', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152118', "province_code" =>' 7056', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152119', "province_code" =>' 7057', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152120', "province_code" =>' 7058', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152121', "province_code" =>' 7059', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152122', "province_code" =>' 7060', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152123', "province_code" =>' 7061', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152124', "province_code" =>' 7062', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152125', "province_code" =>' 7063', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152126', "province_code" =>' 7064', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152127', "province_code" =>' 7065', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152128', "province_code" =>' 7066', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152129', "province_code" =>' 7067', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152130', "province_code" =>' 7068', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152131', "province_code" =>' 7069', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152132', "province_code" =>' 7070', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152133', "province_code" =>' 7071', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152134', "province_code" =>' 7072', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152135', "province_code" =>' 7073', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152136', "province_code" =>' 7074', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152137', "province_code" =>' 7075', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152138', "province_code" =>' 7076', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152139', "province_code" =>' 7077', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152140', "province_code" =>' 7078', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152141', "province_code" =>' 7079', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" =>' No Definido', "code" =>'152142', "province_code" =>' 7080', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}