<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipios')->insert([
            [ "name" => 'Santo Domingo de Guzman', "code" => '141401', "province_code" => '6801', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Azua', "code" => '141402', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Las Charcas', "code" => '141403', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Las Yayas de Viajama', "code" => '141404', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Padre Las Casas', "code" => '141405', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Peralta', "code" => '141406', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sabana Yegua', "code" => '141407', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Pueblo Viejo', "code" => '141408', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Tabara Arriba', "code" => '141409', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Guayabal', "code" => '141410', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Estebania', "code" => '141411', "province_code" => '6802', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Neiba', "code" => '141412', "province_code" => '6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Galvan', "code" => '141413', "province_code" => '6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Tamayo', "code" => '141414', "province_code" => '6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Jaragua', "code" => '141415', "province_code" => '6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Los Rios', "code" => '141416', "province_code" => '6803', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Barahona', "code" => '141417', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Cabral', "code" => '141418', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Enriquillo', "code" => '141419', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Paraiso', "code" => '141420', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Vicente Noble', "code" => '141421', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'El Peñon', "code" => '141422', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'La Cienaga', "code" => '141423', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Fundacion', "code" => '141424', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Las Salinas', "code" => '141425', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Polo', "code" => '141426', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Jaquimeyes', "code" => '141427', "province_code" => '6804', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Dajabon', "code" => '141428', "province_code" => '6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Loma de Cabrera', "code" => '141429', "province_code" => '6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Partido', "code" => '141430', "province_code" => '6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Restauracion', "code" => '141431', "province_code" => '6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'El Pino', "code" => '141432', "province_code" => '6805', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Francisco de Macoris', "code" => '141433', "province_code" => '6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Arenoso', "code" => '141434', "province_code" => '6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Castillo', "code" => '141435', "province_code" => '6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Pimentel', "code" => '141436', "province_code" => '6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Riva', "code" => '141437', "province_code" => '6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Las Guaranas', "code" => '141438', "province_code" => '6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Eugenio Maria de Hostos', "code" => '141439', "province_code" => '6806', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Comendador', "code" => '141440', "province_code" => '6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Banica', "code" => '141441', "province_code" => '6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'El Llano', "code" => '141442', "province_code" => '6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Hondo Valle', "code" => '141443', "province_code" => '6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Pedro Santana', "code" => '141444', "province_code" => '6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Juan Santiago', "code" => '141445', "province_code" => '6807', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'El Seibo', "code" => '141446', "province_code" => '6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Miches', "code" => '141447', "province_code" => '6808', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Moca', "code" => '141448', "province_code" => '6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Cayetano Germosen', "code" => '141449', "province_code" => '6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Gaspar Hernandez', "code" => '141450', "province_code" => '6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Jamao Al Norte', "code" => '141451', "province_code" => '6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Victor', "code" => '141452', "province_code" => '6809', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Jimani', "code" => '141453', "province_code" => '6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Duverge', "code" => '141454', "province_code" => '6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'La Descubierta', "code" => '141455', "province_code" => '6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Postrer Rio', "code" => '141456', "province_code" => '6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Cristobal', "code" => '141457', "province_code" => '6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Mella', "code" => '141458', "province_code" => '6810', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Higuey', "code" => '141459', "province_code" => '6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Rafael del Yuma', "code" => '141460', "province_code" => '6811', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'La Romana', "code" => '141461', "province_code" => '6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Guaymate', "code" => '141462', "province_code" => '6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Hermosa', "code" => '141463', "province_code" => '6812', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'La Vega', "code" => '141464', "province_code" => '6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Constanza', "code" => '141465', "province_code" => '6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Jarabacoa', "code" => '141466', "province_code" => '6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Jima Abajo', "code" => '141467', "province_code" => '6813', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Nagua', "code" => '141468', "province_code" => '6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Cabrera', "code" => '141469', "province_code" => '6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'El Factor', "code" => '141470', "province_code" => '6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Rio San Juan', "code" => '141471', "province_code" => '6814', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Monte Cristi', "code" => '141472', "province_code" => '6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Castañuelas', "code" => '141473', "province_code" => '6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Guayubín', "code" => '141474', "province_code" => '6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Las Matas de Santa Cruz', "code" => '141475', "province_code" => '6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Pepillo Salcedo', "code" => '141476', "province_code" => '6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Vasquez', "code" => '141477', "province_code" => '6815', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Pedernales', "code" => '141478', "province_code" => '6816', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Oviedo', "code" => '141479', "province_code" => '6816', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Bani', "code" => '141480', "province_code" => '6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Nizao', "code" => '141481', "province_code" => '6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Matanzas', "code" => '141482', "province_code" => '6817', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Puerto Plata', "code" => '141483', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Altamira', "code" => '141484', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Guananico', "code" => '141485', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Imbert', "code" => '141486', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Los Hidalgos', "code" => '141487', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Luperon', "code" => '141488', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sosua', "code" => '141489', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Isabela', "code" => '141490', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Montellano', "code" => '141491', "province_code" => '6818', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Salcedo', "code" => '141492', "province_code" => '6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Tenares', "code" => '141493', "province_code" => '6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Tapia', "code" => '141494', "province_code" => '6819', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Samana', "code" => '141495', "province_code" => '6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sanchez', "code" => '141496', "province_code" => '6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Las Terrenas', "code" => '141497', "province_code" => '6820', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Cristobal', "code" => '141498', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sabana Grande de Palenque', "code" => '141499', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Bajos de Haina', "code" => '141500', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Cambita Garabitos', "code" => '141501', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Altagracia', "code" => '141502', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Yaguate', "code" => '141503', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Gregorio de Nigua', "code" => '141504', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Los Cacaos', "code" => '141505', "province_code" => '6821', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Juan', "code" => '141506', "province_code" => '6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Bohechio', "code" => '141507', "province_code" => '6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'El Cercado', "code" => '141508', "province_code" => '6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Juan de Herrera', "code" => '141509', "province_code" => '6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Las Matas de Farfan', "code" => '141510', "province_code" => '6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Vallejuelo', "code" => '141511', "province_code" => '6822', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Pedro de Macoris', "code" => '141512', "province_code" => '6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Los Llanos', "code" => '141513', "province_code" => '6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Ramon Santana', "code" => '141514', "province_code" => '6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Consuelo', "code" => '141515', "province_code" => '6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Quisqueya', "code" => '141516', "province_code" => '6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Guayacanes', "code" => '141517', "province_code" => '6823', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Cotui', "code" => '141518', "province_code" => '6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Cevicos', "code" => '141519', "province_code" => '6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Fantino', "code" => '141520', "province_code" => '6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa La Mata', "code" => '141521', "province_code" => '6824', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Santiago', "code" => '141522', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Bisona', "code" => '141523', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Janico', "code" => '141524', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Licey al Medio', "code" => '141525', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Jose de Las Matas', "code" => '141526', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Tamboril', "code" => '141527', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Gonzalez', "code" => '141528', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Puñal', "code" => '141529', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sabana de La Mar', "code" => '141530', "province_code" => '6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Boca Chica', "code" => '141531', "province_code" => '6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sabana Iglesia', "code" => '141532', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Baitoa', "code" => '141533', "province_code" => '6825', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Mao', "code" => '141534', "province_code" => '6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Yamasa', "code" => '141535', "province_code" => '6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Ignacio de Sabaneta', "code" => '141536', "province_code" => '6826', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Villa Los Almacigos', "code" => '141537', "province_code" => '6826', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Moncion', "code" => '141538', "province_code" => '6826', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Laguna Salada', "code" => '141539', "province_code" => '6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Maimon', "code" => '141540', "province_code" => '6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Bayaguana', "code" => '141541', "province_code" => '6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sabana Grande de Boya', "code" => '141542', "province_code" => '6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Peralvillo', "code" => '141543', "province_code" => '6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'El Valle', "code" => '141544', "province_code" => '6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Pedro Brand', "code" => '141545', "province_code" => '6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Esperanza', "code" => '141546', "province_code" => '6827', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Bonao', "code" => '141547', "province_code" => '6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Monte Plata', "code" => '141548', "province_code" => '6829', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Antonio de Guerra', "code" => '141549', "province_code" => '6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Los Alcarrizos', "code" => '141550', "province_code" => '6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Piedra Blanca', "code" => '141551', "province_code" => '6828', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Hato Mayor', "code" => '141552', "province_code" => '6830', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'San Jose de Ocoa', "code" => '141553', "province_code" => '6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Sabana Larga', "code" => '141554', "province_code" => '6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Santo Domingo Este', "code" => '141555', "province_code" => '6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Santo Domingo Oeste', "code" => '141556', "province_code" => '6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Santo Domingo Norte', "code" => '141557', "province_code" => '6832', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'Rancho Arriba', "code" => '141558', "province_code" => '6831', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141559', "province_code" => '6833', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141560', "province_code" => '6834', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141561', "province_code" => '6835', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141562', "province_code" => '6836', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141563', "province_code" => '6837', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141564', "province_code" => '6838', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141565', "province_code" => '6839', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141566', "province_code" => '6840', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141567', "province_code" => '6841', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141568', "province_code" => '6842', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141569', "province_code" => '6843', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141570', "province_code" => '6844', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141571', "province_code" => '6845', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141572', "province_code" => '6846', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141573', "province_code" => '6847', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141574', "province_code" => '6848', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141575', "province_code" => '6849', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141576', "province_code" => '6850', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141577', "province_code" => '6851', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141578', "province_code" => '6852', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141579', "province_code" => '6853', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141580', "province_code" => '6854', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141581', "province_code" => '6855', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141582', "province_code" => '6856', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141583', "province_code" => '6857', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141584', "province_code" => '6858', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141585', "province_code" => '6859', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141586', "province_code" => '6860', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141587', "province_code" => '6861', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141588', "province_code" => '6862', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141589', "province_code" => '6863', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141590', "province_code" => '6864', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141591', "province_code" => '6865', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141592', "province_code" => '6866', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141593', "province_code" => '6867', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141594', "province_code" => '6868', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141595', "province_code" => '6869', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141596', "province_code" => '6870', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141597', "province_code" => '6871', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141598', "province_code" => '6872', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141599', "province_code" => '6873', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141600', "province_code" => '6874', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141601', "province_code" => '6875', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141602', "province_code" => '6876', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141603', "province_code" => '6877', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141604', "province_code" => '6878', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141605', "province_code" => '6879', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141606', "province_code" => '6880', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141607', "province_code" => '6881', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141608', "province_code" => '6882', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141609', "province_code" => '6883', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141610', "province_code" => '6884', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141611', "province_code" => '6885', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141612', "province_code" => '6886', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141613', "province_code" => '6887', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141614', "province_code" => '6888', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141615', "province_code" => '6889', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141616', "province_code" => '6890', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141617', "province_code" => '6891', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141618', "province_code" => '6892', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141619', "province_code" => '6893', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141620', "province_code" => '6894', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141621', "province_code" => '6895', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141622', "province_code" => '6896', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141623', "province_code" => '6897', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141624', "province_code" => '6898', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141625', "province_code" => '6899', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141626', "province_code" => '6900', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141627', "province_code" => '6901', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141628', "province_code" => '6902', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141629', "province_code" => '6903', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141630', "province_code" => '6904', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141631', "province_code" => '6905', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141632', "province_code" => '6906', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141633', "province_code" => '6907', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141634', "province_code" => '6908', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141635', "province_code" => '6909', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141636', "province_code" => '6910', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141637', "province_code" => '6911', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141638', "province_code" => '6912', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141639', "province_code" => '6913', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141640', "province_code" => '6914', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141641', "province_code" => '6915', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141642', "province_code" => '6916', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141643', "province_code" => '6917', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141644', "province_code" => '6918', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141645', "province_code" => '6919', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141646', "province_code" => '6920', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141647', "province_code" => '6921', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141648', "province_code" => '6922', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141649', "province_code" => '6923', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141650', "province_code" => '6924', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141651', "province_code" => '6925', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141652', "province_code" => '6926', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141653', "province_code" => '6927', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141654', "province_code" => '6928', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141655', "province_code" => '6929', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141656', "province_code" => '6930', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141657', "province_code" => '6931', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141658', "province_code" => '6932', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141659', "province_code" => '6933', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141660', "province_code" => '6934', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141661', "province_code" => '6935', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141662', "province_code" => '6936', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141663', "province_code" => '6937', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141664', "province_code" => '6938', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141665', "province_code" => '6939', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141666', "province_code" => '6940', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141667', "province_code" => '6941', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141668', "province_code" => '6942', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141669', "province_code" => '6943', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141670', "province_code" => '6944', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141671', "province_code" => '6945', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141672', "province_code" => '6946', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141673', "province_code" => '6947', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141674', "province_code" => '6948', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141675', "province_code" => '6949', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141676', "province_code" => '6950', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141677', "province_code" => '6951', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141678', "province_code" => '6952', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141679', "province_code" => '6953', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141680', "province_code" => '6954', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141681', "province_code" => '6955', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141682', "province_code" => '6956', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141683', "province_code" => '6957', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141684', "province_code" => '6958', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141685', "province_code" => '6959', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141686', "province_code" => '6960', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141687', "province_code" => '6961', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141688', "province_code" => '6962', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141689', "province_code" => '6963', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141690', "province_code" => '6964', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141691', "province_code" => '6965', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141692', "province_code" => '6966', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141693', "province_code" => '6967', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141694', "province_code" => '6968', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141695', "province_code" => '6969', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141696', "province_code" => '6970', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141697', "province_code" => '6971', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141698', "province_code" => '6972', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141699', "province_code" => '6973', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141700', "province_code" => '6974', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141701', "province_code" => '6975', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141702', "province_code" => '6976', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141703', "province_code" => '6977', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141704', "province_code" => '6978', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141705', "province_code" => '6979', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141706', "province_code" => '6980', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141707', "province_code" => '6981', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141708', "province_code" => '6982', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141709', "province_code" => '6983', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141710', "province_code" => '6984', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141711', "province_code" => '6985', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141712', "province_code" => '6986', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141713', "province_code" => '6987', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141714', "province_code" => '6988', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141715', "province_code" => '6990', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141716', "province_code" => '6991', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141717', "province_code" => '6992', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141718', "province_code" => '6993', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141719', "province_code" => '6994', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141720', "province_code" => '6995', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141721', "province_code" => '6996', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141722', "province_code" => '6997', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141723', "province_code" => '6998', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141724', "province_code" => '6999', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141725', "province_code" => '7000', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141726', "province_code" => '7001', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141727', "province_code" => '7002', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141728', "province_code" => '7003', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141729', "province_code" => '7004', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141730', "province_code" => '7005', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141731', "province_code" => '7006', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141732', "province_code" => '7007', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141733', "province_code" => '7008', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141734', "province_code" => '7009', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141735', "province_code" => '7010', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141736', "province_code" => '7011', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141737', "province_code" => '7012', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141738', "province_code" => '7013', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141739', "province_code" => '7014', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141740', "province_code" => '7015', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141741', "province_code" => '7016', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141742', "province_code" => '7017', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141743', "province_code" => '7018', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141744', "province_code" => '7019', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141745', "province_code" => '7020', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            #N/A
            [ "name" => 'No Definido', "code" => '141747', "province_code" => '7021', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141748', "province_code" => '7022', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141749', "province_code" => '7023', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141750', "province_code" => '7024', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141751', "province_code" => '7025', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141752', "province_code" => '7026', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141753', "province_code" => '7027', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141754', "province_code" => '7028', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141755', "province_code" => '7029', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141756', "province_code" => '7030', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141757', "province_code" => '7031', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141758', "province_code" => '7032', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141759', "province_code" => '7033', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141760', "province_code" => '7034', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141761', "province_code" => '7035', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141762', "province_code" => '7036', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141763', "province_code" => '7037', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141764', "province_code" => '7038', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141765', "province_code" => '7039', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141766', "province_code" => '7040', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141767', "province_code" => '7041', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141768', "province_code" => '7042', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141769', "province_code" => '7043', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141770', "province_code" => '7044', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141771', "province_code" => '7045', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141772', "province_code" => '7046', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141773', "province_code" => '7047', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141774', "province_code" => '7048', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141775', "province_code" => '7049', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141776', "province_code" => '7050', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141777', "province_code" => '7051', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141778', "province_code" => '7052', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141779', "province_code" => '7053', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141780', "province_code" => '7054', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141781', "province_code" => '7055', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141782', "province_code" => '7056', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141783', "province_code" => '7057', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141784', "province_code" => '7058', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141785', "province_code" => '7059', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141786', "province_code" => '7060', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141787', "province_code" => '7061', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141788', "province_code" => '7062', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141789', "province_code" => '7063', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141790', "province_code" => '7064', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141791', "province_code" => '7065', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141792', "province_code" => '7066', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141793', "province_code" => '7067', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141794', "province_code" => '7068', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141795', "province_code" => '7069', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141796', "province_code" => '7070', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141797', "province_code" => '7071', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141798', "province_code" => '7072', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141799', "province_code" => '7073', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141800', "province_code" => '7074', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141801', "province_code" => '7075', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141802', "province_code" => '7076', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141803', "province_code" => '7077', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141804', "province_code" => '7078', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141805', "province_code" => '7079', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            [ "name" => 'No Definido', "code" => '141806', "province_code" => '7080', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}