<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ProvinciasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('provincias')->insert([
            [ "name" => 'Distrito Nacional', "country_code" => '8089' , "code" => '6801',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Azua', "country_code" => '8089' , "code" => '6802',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Baoruco', "country_code" => '8089' , "code" => '6803',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Barahona', "country_code" => '8089' , "code" => '6804',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Dajabon', "country_code" => '8089' , "code" => '6805',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Duarte', "country_code" => '8089' , "code" => '6806',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Elias Piña', "country_code" => '8089' , "code" => '6807',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'El Seibo', "country_code" => '8089' , "code" => '6808',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Espaillat', "country_code" => '8089' , "code" => '6809',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Independencia', "country_code" => '8089' , "code" => '6810',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'La Altagracia', "country_code" => '8089' , "code" => '6811',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'La Romana', "country_code" => '8089' , "code" => '6812',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'La Vega', "country_code" => '8089' , "code" => '6813',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Maria Trinidad Sanchez', "country_code" => '8089' , "code" => '6814',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Monte Cristi', "country_code" => '8089' , "code" => '6815',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Pedernales', "country_code" => '8089' , "code" => '6816',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Peravia', "country_code" => '8089' , "code" => '6817',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Puerto Plata', "country_code" => '8089' , "code" => '6818',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Hermanas Mirabal', "country_code" => '8089' , "code" => '6819',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Samana', "country_code" => '8089' , "code" => '6820',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'San Cristobal', "country_code" => '8089' , "code" => '6821',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'San Juan', "country_code" => '8089' , "code" => '6822',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'San Pedro de Macoris', "country_code" => '8089' , "code" => '6823',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Sanchez Ramirez', "country_code" => '8089' , "code" => '6824',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Santiago', "country_code" => '8089' , "code" => '6825',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Santiago Rodriguez', "country_code" => '8089' , "code" => '6826',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Valverde', "country_code" => '8089' , "code" => '6827',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Monseñor Nouel', "country_code" => '8089' , "code" => '6828',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Monte Plata', "country_code" => '8089' , "code" => '6829',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Hato Mayor', "country_code" => '8089' , "code" => '6830',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'San Jose de Ocoa', "country_code" => '8089' , "code" => '6831',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'Santo Domingo', "country_code" => '8089' , "code" => '6832',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7901' , "code" => '6833',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7902' , "code" => '6834',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7903' , "code" => '6835',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7904' , "code" => '6836',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7905' , "code" => '6837',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7906' , "code" => '6838',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7907' , "code" => '6839',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7908' , "code" => '6840',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7909' , "code" => '6841',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7910' , "code" => '6842',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7911' , "code" => '6843',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7912' , "code" => '6844',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7913' , "code" => '6845',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7914' , "code" => '6846',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7915' , "code" => '6847',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7916' , "code" => '6848',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7917' , "code" => '6849',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7918' , "code" => '6850',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7919' , "code" => '6851',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7920' , "code" => '6852',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7921' , "code" => '6853',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7922' , "code" => '6854',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7923' , "code" => '6855',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7924' , "code" => '6856',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7925' , "code" => '6857',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7926' , "code" => '6858',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7927' , "code" => '6859',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7928' , "code" => '6860',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7929' , "code" => '6861',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7930' , "code" => '6862',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7931' , "code" => '6863',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7932' , "code" => '6864',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7933' , "code" => '6865',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7934' , "code" => '6866',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7935' , "code" => '6867',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7936' , "code" => '6868',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7937' , "code" => '6869',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7938' , "code" => '6870',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7939' , "code" => '6871',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7940' , "code" => '6872',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7941' , "code" => '6873',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7942' , "code" => '6874',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7943' , "code" => '6875',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7944' , "code" => '6876',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7945' , "code" => '6877',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7946' , "code" => '6878',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7947' , "code" => '6879',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7948' , "code" => '6880',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7949' , "code" => '6881',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7950' , "code" => '6882',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7951' , "code" => '6883',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7952' , "code" => '6884',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7953' , "code" => '6885',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7954' , "code" => '6886',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7955' , "code" => '6887',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7956' , "code" => '6888',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7957' , "code" => '6889',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7958' , "code" => '6890',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7959' , "code" => '6891',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7960' , "code" => '6892',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7961' , "code" => '6893',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7962' , "code" => '6894',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7963' , "code" => '6895',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7964' , "code" => '6896',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7965' , "code" => '6897',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7966' , "code" => '6898',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7967' , "code" => '6899',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7968' , "code" => '6900',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7969' , "code" => '6901',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7970' , "code" => '6902',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7971' , "code" => '6903',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7972' , "code" => '6904',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7973' , "code" => '6905',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7974' , "code" => '6906',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7975' , "code" => '6907',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7976' , "code" => '6908',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7977' , "code" => '6909',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7978' , "code" => '6910',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7979' , "code" => '6911',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7980' , "code" => '6912',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7981' , "code" => '6913',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7982' , "code" => '6914',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7983' , "code" => '6915',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7984' , "code" => '6916',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7985' , "code" => '6917',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7986' , "code" => '6918',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7987' , "code" => '6919',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7988' , "code" => '6920',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7989' , "code" => '6921',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7990' , "code" => '6922',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7991' , "code" => '6923',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7992' , "code" => '6924',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7993' , "code" => '6925',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7994' , "code" => '6926',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7995' , "code" => '6927',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7996' , "code" => '6928',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7997' , "code" => '6929',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7998' , "code" => '6930',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '7999' , "code" => '6931',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8000' , "code" => '6932',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8001' , "code" => '6933',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8002' , "code" => '6934',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8003' , "code" => '6935',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8004' , "code" => '6936',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8005' , "code" => '6937',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8006' , "code" => '6938',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8007' , "code" => '6939',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8008' , "code" => '6940',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8009' , "code" => '6941',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8010' , "code" => '6942',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8011' , "code" => '6943',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8012' , "code" => '6944',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8013' , "code" => '6945',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8014' , "code" => '6946',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8015' , "code" => '6947',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8016' , "code" => '6948',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8017' , "code" => '6949',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8018' , "code" => '6950',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8019' , "code" => '6951',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8020' , "code" => '6952',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8021' , "code" => '6953',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8022' , "code" => '6954',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8023' , "code" => '6955',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8024' , "code" => '6956',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8025' , "code" => '6957',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8026' , "code" => '6958',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8027' , "code" => '6959',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8028' , "code" => '6960',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8029' , "code" => '6961',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8030' , "code" => '6962',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8031' , "code" => '6963',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8032' , "code" => '6964',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8033' , "code" => '6965',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8034' , "code" => '6966',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8035' , "code" => '6967',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8036' , "code" => '6968',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8037' , "code" => '6969',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8038' , "code" => '6970',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8039' , "code" => '6971',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8040' , "code" => '6972',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8041' , "code" => '6973',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8042' , "code" => '6974',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8043' , "code" => '6975',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8044' , "code" => '6976',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8045' , "code" => '6977',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8046' , "code" => '6978',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8047' , "code" => '6979',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8048' , "code" => '6980',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8049' , "code" => '6981',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8050' , "code" => '6982',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8051' , "code" => '6983',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8052' , "code" => '6984',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8053' , "code" => '6985',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8054' , "code" => '6986',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8055' , "code" => '6987',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8056' , "code" => '6988',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8057' , "code" => '6989',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8058' , "code" => '6990',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8059' , "code" => '6991',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8060' , "code" => '6992',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8061' , "code" => '6993',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8062' , "code" => '6994',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8063' , "code" => '6995',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8064' , "code" => '6996',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8065' , "code" => '6997',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8066' , "code" => '6998',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8067' , "code" => '6999',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8068' , "code" => '7000',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8069' , "code" => '7001',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8070' , "code" => '7002',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8071' , "code" => '7003',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8072' , "code" => '7004',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8073' , "code" => '7005',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8074' , "code" => '7006',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8075' , "code" => '7007',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8076' , "code" => '7008',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8077' , "code" => '7009',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8078' , "code" => '7010',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8079' , "code" => '7011',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8080' , "code" => '7012',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8081' , "code" => '7013',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8082' , "code" => '7014',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8083' , "code" => '7015',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8084' , "code" => '7016',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8085' , "code" => '7017',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8086' , "code" => '7018',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8087' , "code" => '7019',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8088' , "code" => '7020',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8090' , "code" => '7021',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8091' , "code" => '7022',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8092' , "code" => '7023',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8093' , "code" => '7024',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8094' , "code" => '7025',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8095' , "code" => '7026',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8096' , "code" => '7027',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8097' , "code" => '7028',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8098' , "code" => '7029',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8099' , "code" => '7030',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8100' , "code" => '7031',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8101' , "code" => '7032',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8102' , "code" => '7033',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8103' , "code" => '7034',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8104' , "code" => '7035',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8105' , "code" => '7036',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8106' , "code" => '7037',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8107' , "code" => '7038',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8108' , "code" => '7039',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8109' , "code" => '7040',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8110' , "code" => '7041',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8111' , "code" => '7042',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8112' , "code" => '7043',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8113' , "code" => '7044',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8114' , "code" => '7045',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8115' , "code" => '7046',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8116' , "code" => '7047',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8117' , "code" => '7048',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8118' , "code" => '7049',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8119' , "code" => '7050',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8120' , "code" => '7051',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8121' , "code" => '7052',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8122' , "code" => '7053',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8123' , "code" => '7054',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8124' , "code" => '7055',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8125' , "code" => '7056',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8126' , "code" => '7057',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8127' , "code" => '7058',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8128' , "code" => '7059',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8129' , "code" => '7060',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8130' , "code" => '7061',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8131' , "code" => '7062',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8132' , "code" => '7063',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8133' , "code" => '7064',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8134' , "code" => '7065',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8135' , "code" => '7066',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8136' , "code" => '7067',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8137' , "code" => '7068',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8138' , "code" => '7069',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8139' , "code" => '7070',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8140' , "code" => '7071',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8141' , "code" => '7072',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8142' , "code" => '7073',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8143' , "code" => '7074',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8144' , "code" => '7075',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8145' , "code" => '7076',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8146' , "code" => '7077',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8147' , "code" => '7078',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8148' , "code" => '7079',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
            [ "name" => 'No Definido', "country_code" => '8149' , "code" => '7080',  "created_at" => Carbon::now(), "updated_at" => Carbon::now()],
        ]);
    }
}