---
version: "3.4"
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./local/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      # - mysql_laravel
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
